### ISSUE TITLE
Setting a filename

### ISSUE THREAD

**Issue by matteosuppo** [mjumbewu/django-rest-framework-csv#15]
Calling the api with ?format=csv makes you download a file, which is great.

Is there a simple way to set what the filename will be?

**Comment by int-ua** [comment]
Can you please add an example?

**Comment by matteosuppo** [comment]
```
def finalize_response(self, request, response, *args, **kwargs):
    response['Content-Disposition'] = "attachment; filename=%s" % (self.get_filename())
```

**Comment by danilke** [comment]
Is some simple way to set title with "*.csv" to all views when I use:  

```
REST_FRAMEWORK = {
    # specifying the renderers
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework_csv.renderers.CSVRenderer',
    ),
}

```

**Comment by C0DK** [comment]
couldn't the readme please provide such an example?

**Comment by gretkierewicz** [comment]
> ```
> def finalize_response(self, request, response, *args, **kwargs):
>     response['Content-Disposition'] = "attachment; filename=%s" % (self.get_filename())
> ```

I'm affraid ViewSets like ModelViewSet dont have such method. 
Is there any chance for a hint in case of using ViewSets?
