### ISSUE TITLE
Is it possible to use StreamingHttpResponse?

### ISSUE THREAD

**Issue by buddylindsey** [mjumbewu/django-rest-framework-csv#16]
We are currently using `django-rest-framework-csv` for csv export, but we have found we have some large datasets that eventually lead to a timeout between nginx and our app. Is it possible to use `StreamingHttpResponse` for returning a csv file using this library?

**Comment by frewsxcv** [comment]
https://github.com/mjumbewu/django-rest-framework-csv/blob/ee9a05e103c5d1c08216ef10449a25163ff1d1b1/rest_framework_csv/renderers.py#L183

There is now a `CSVStreamingRenderer`. This can probably be closed?
