### ISSUE TITLE
tablize(data) doesn't return headers if data is empty

### ISSUE THREAD

**Issue by dbkaplun** [mjumbewu/django-rest-framework-csv#32]

**Comment by munendrasn** [comment]
@dbkaplun
in renderers.py 
```python
# in render function
if data is None: 
     return ''      # returned, no tablize is done if data is empty i.e, None
```
If data is empty ```''```is returned and  ```tablize(data)``` is not called.
so, there wont be any `data headers`.
Hope this answers your question.
