### ISSUE TITLE
version 1.3.3 on pip and github are different

### ISSUE THREAD

**Issue by munendrasn** [mjumbewu/django-rest-framework-csv#33]
pip install of django-restformwork-csv doesn't have CSVStreamingRenderer class whereas Git hub repo has it...

**Comment by mjumbewu** [comment]
thanks for reporting. i pushed up a new version (1.3.4) to PyPI this morning (https://github.com/mjumbewu/django-rest-framework-csv/issues/18#issuecomment-116312619).
