### ISSUE TITLE
Changing the CSV delimiter is hard when using DRF-CSV from a DRF app

### ISSUE THREAD

**Issue by elnygren** [mjumbewu/django-rest-framework-csv#37]
I noticed that the CSV renderer returns broken data if any field in the JSON data contains a comma. 

Also, it is not possible to change the delimiter (to say `;`) with any configuration option.

**Comment by elnygren** [comment]
Ah, the mistake on the comma part was mine (it is handled appropriately by django-rest-framework-csv). 

However, it would still be a nice feature to have a configurable option to change the delimiter. 

Apparently `writer_opts` is accepted [here](https://github.com/mjumbewu/django-rest-framework-csv/blob/master/rest_framework_csv/renderers.py#L26) as a param. However, it is hard to give `.renderer()` method a custom param like that from DRF side. (one would have to reimplement `Response.rendered_content()`

**Comment by elnygren** [comment]
okey I have this kind of solution for myself:

```python
class MyViewSet(..):
  renderer_classes = renderer_classes = api_settings.DEFAULT_RENDERER_CLASSES + [r.CSVRenderer, ]

  def __init__(self, *args, **kwargs):
    r.CSVRenderer.writer_opts = {
      'quoting': csv.QUOTE_ALL,
      'quotechar': '"',
      'delimiter': ';'
      }
    super(MyViewSet, self).__init__(*args, **kwargs)
```
Implementation (all tox tests pass):
https://github.com/elnygren/django-rest-framework-csv/commit/eebe6d5b5236524a65f6b0761a000647425b211d

I suppose a better way would be to use the Django settings though? (which is why I haven't created a PR)

**Comment by mjumbewu** [comment]
I think there are a number of "right" ways to do this. I just made a change that supports two of those ways though:

1. The way that you have laid out above will now work as of version 1.4.1
2. You can also use the `renderer_context`, which would look something like:

```python
class MyViewSet(..):
  renderer_classes = renderer_classes = api_settings.DEFAULT_RENDERER_CLASSES + [r.CSVRenderer, ]

  def get_renderer_context(self):
    context = super().get_renderer_context()
    context['writer_opts'] = {
      'quoting': csv.QUOTE_ALL,
      'quotechar': '"',
      'delimiter': ';'
      }
    return context
```

If you want to change the behavior project-wide, I suppose you could just override the value once at the top of your *views.py*, i.e.:

```python
r.CSVRenderer.writer_opts = {
  'quoting': csv.QUOTE_ALL,
  'quotechar': '"',
  'delimiter': ';'
  }
```

Though, in that case you're right that using the Django settings might be more appropriate (but is also not implemented right now).
