### ISSUE TITLE
Customize file name

### ISSUE THREAD

**Issue by jangeador** [mjumbewu/django-rest-framework-csv#38]
Is there a place to specify a filename or something I can override to tell the renderer which file name to use? I looked at the source and I could not find the place where to speficify this. Thanks.

**Comment by thinkt4nk** [comment]
@jangeador if I understand your problem, this isn't really the responsibility of the renderer.  You probably want to set the following response header to get the effect you desire:

`Content-Disposition: attachment; filename=<FILENAME>`
