### ISSUE TITLE
Unicode issues in production (with wsgi)

### ISSUE THREAD

**Issue by brandonrobertz** [mjumbewu/django-rest-framework-csv#43]
For parsing, unicode all works great in the unit tests, but there's one huge problem: in the unit tests the `stream` object passed to `CSVParser.parse` is a `StringIO`, while in production (apache/wsgi) it's actually an instance of `<class 'django.core.handlers.wsgi.WSGIRequest'>`. The end result is the unit test pass, showing unicode success, but when you POST some unicode to an endpoint using the parser you get the dreaded:

`{"detail":"CSV parse error - 'ascii' codec can't decode byte 0xe2 in position 17136: ordinal not in range(128)"}`

I wrote a stopgap hotfix in a fork (https://github.com/alertmedia/django-rest-framework-csv), but it breaks all the unit tests, which are written using the `StringIO` streams. I also used unicodecsv library, not builtin csv.

Any ideas on reconciliation here?

**Comment by mjumbewu** [comment]
Using your fork, I think I fixed all the tests. I pushed up into the [unicode-io](https://github.com/mjumbewu/django-rest-framework-csv/tree/unicode-io) branch. I'm going to do some more testing, before merging into master.
