### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by davidmir** [mjumbewu/django-rest-framework-csv#48]
Hi,

In the file views.py I think It should be like this: 

`renderer_classes = (r.CSVRenderer, ) + tuple(api_settings.DEFAULT_RENDERER_CLASSES)
`

**Comment by munendrasn** [comment]
@davidmir ,
The syntax used in `views.py` is correct because,
`api_settings.DEFAULT_RENDERER_CLASSES` is already a tuple.
