### ISSUE TITLE
when a file is downloaded by any browser on Windows the file has no format , how do I solve

### ISSUE THREAD

**Issue by lucaslamounier** [mjumbewu/django-rest-framework-csv#52]
I use the api rest to perform data download : http://localhost:8000/api/estatisticas/subcategorias/?format=csv&uf=&categoria=&subcategoria=&ano=2016 but when the user downloads the file browser for the Windows file comes without the .csv extension

**Comment by mjumbewu** [comment]
Similar issue to #56. See response there.
