### ISSUE TITLE
TypeError: can only concatenate tuple (not "list") to tuple

### ISSUE THREAD

**Issue by alvaromlg** [mjumbewu/django-rest-framework-csv#64]
Is your README example correct?

Had to replace this line
`(csv_render.CSVRenderer, ) + api_settings.DEFAULT_RENDERER_CLASSES`

with this one
`(csv_render.CSVRenderer, ) + tuple(api_settings.DEFAULT_RENDERER_CLASSES)`

> TypeError: can only concatenate tuple (not "list") to tuple

**Comment by mjumbewu** [comment]
ah, you may be right. it's possible that `DEFAULT_RENDERER_CLASSES` used to be a tuple in a prior version of DRF but is now a list. explicitly casting is safer in the example anyway.
