### ISSUE TITLE
how do I output a list field as a single columns output rather than multiple columns

### ISSUE THREAD

**Issue by KushGoyal** [mjumbewu/django-rest-framework-csv#65]
I have many list fields in my model. Each item in list field takes one column in the spreadsheet. How can I modify the renderer so that list field items are rendered as a single column with comma separated values.

**Comment by mjumbewu** [comment]
Hm, there's not really a configurable way to do this right now. At the moment what you'd have to do is subclass the `CSVRenderer` and override the `flatten_list` method to read something like:

```python
    def flatten_list(self, l):
        flat_list = {'': ', '.join(l)}
        return flat_list
```

The resulting renderer should do what you want.

**Comment by KushGoyal** [comment]
@mjumbewu Thanks that did it!

**Comment by sinistag** [comment]
Nice, maybe you should add this to the readme, I almost opened a new issue looking for this.

(maybe change to `', '.join(str(ele) for ele in l)` to increase compatibility)

**Comment by elebumm** [comment]
I would love to see an example of real usage of this method!
