### ISSUE TITLE
Field Order / Headers from the Serializer

### ISSUE THREAD

**Issue by rjemanuele** [mjumbewu/django-rest-framework-csv#74]
Is it possible to get the the serializer that is the `CSVRenderer` is rendering to use its `fields` attribute to specify the `header` ordering?

I'm trying to figure out if I can do that to define the ordering in a single place?

**Comment by rjemanuele** [comment]
It might also be something to specify the field order in the query parameters.  (Along the same lines, it could even be great to specify a subset of the available field if an csv user only needs a few fields.)

**Comment by C0DK** [comment]
For me it seems weird that you want alphabetically ordered fields, but it's fair if some people want that - but why not make it based on the serializer as the rest of DRF does? so if you want them alphabetical order, then you simply order them alphabetically in the serializer.

It's really difficult to change the fields in the viewset currently. Currently i am doing:

def get_renderer_context(self):
        context = super().get_renderer_context()
        # force the order from the serializer.
        context['header'] = self.serializer_class.Meta.fields
        return context

But that is really hacky (and seems weird that i have to force it to do the 'default'. Also this was problematic (the code above) when i went to change fields dynamically in the serializer making the seperation of responsibilities really difficult.

**Comment by KushGoyal** [comment]
@C0DK thanks for the solution, but this seems to fail with nested serializers. The field defined as a nested serializer fails to serialize and the output is a blank.
