### ISSUE TITLE
Releases potentially causing the project to appear unmaintained

### ISSUE THREAD

**Issue by tim-schilling** [mjumbewu/django-rest-framework-csv#88]
Hi @mjumbewu and team, I wanted to let you know it took me a bit to realize that this project is under active development since the latest "release" was 1.3.3 and that's what GitHub decides to show on the front page on the right side. After seeing the latest commit was from May, I checked the tags and saw there have been a number of new versions since 1.3.3.

I'm not sure of the best solution here, but wanted to raise the issue since it's probably difficult to notice if you're a regular contributor.

![Screenshot from 2021-08-04 13-53-20](https://user-images.githubusercontent.com/1281215/128238546-3de10ed8-4b83-4d5d-8e7f-9a9fb5cd3e86.png)

**Comment by mjumbewu** [comment]
Noted. I hadn't been paying attention to releases lately. Thanks for the heads up.
