### ISSUE TITLE
Add support Django 3.2

### ISSUE THREAD

**Issue by MaferMazu** [mjumbewu/django-rest-framework-csv#90]
In OpenedX the libraries are being upgraded to migrate to Django 3.2, I would like to add the necessary changes in the tests to ensure it.

I did a PR #89 , I would like to know your opinion and if something else is needed to support Django 3.2

**Comment by mjumbewu** [comment]
@MaferMazu Very sorry that the fix took so long to get in, but it should be up-to-date as of version 3.0.0
