### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by Aiky30** [mjumbewu/django-rest-framework-csv#97]
This package is recommended by the official DRf docs: https://www.django-rest-framework.org/api-guide/renderers/#csv

I have concerns with the compatibility in the setup.py file stating python 3.5, we now have 3.11. 

Also there are Pr's for CI test django 3.x support, we're now looking at 4.x...

The last change at time of writing this is May 2021.

If anyone reads this and either forks or knows of a good alternative please provide a list in the comments below, it might be that the DRF site also needs to change the recommended package.

**Comment by GabDug** [comment]
Hey @Aiky30,

I made a [fork](https://github.com/GabDug/django-rest-framework-csv), targeting current Python and Django versions. It also removes deprecated attributes and parameters. [It's WIP but available on Pypi](https://pypi.org/project/djangorestframework-csv-3/3.0.0.dev1/) if you're willing to give it a try.

Beware, they may be breaking changes if you did not use UTF-8.
